{\rtf1\ansi\ansicpg936\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww30040\viewh16560\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # Site settings\
title: \uc0\u23433 \u22958 \u30340 \u21338 \u23458 \
email: your-email@example.com\
description: \uc0\u35760 \u24405 \u29983 \u27963 \u28857 \u28404 \u65292 \u20998 \u20139 \u25216 \u26415 \u24515 \u24471 \
baseurl: ""\
url: "https://annlihui.github.io"\
twitter_username: \
github_username: Annlihui\
\
# Build settings\
markdown: kramdown\
highlighter: rouge\
theme: minima\
plugins:\
  - jekyll-feed\
  - jekyll-sitemap\
  - jekyll-seo-tag\
\
# Exclude from processing\
exclude:\
  - Gemfile\
  - Gemfile.lock\
  - node_modules\
  - vendor/bundle/\
  - vendor/cache/\
  - vendor/gems/\
  - vendor/ruby/\
\
# Collection settings\
collections:\
  posts:\
    output: true\
    permalink: /:categories/:year/:month/:day/:title/\
\
# Pagination\
paginate: 5\
paginate_path: "/page:num/"\
\
# Comments (\uc0\u21487 \u36873 \u65292 \u22914 \u26524 \u38656 \u35201 \u35780 \u35770 \u21151 \u33021 )\
# disqus:\
#   shortname: your-disqus-shortname\
\
# Google Analytics (\uc0\u21487 \u36873 )\
# google_analytics: UA-XXXXXXXXX-X\
\
# Social links\
social_links:\
  github: Annlihui\
  # twitter: yourusername\
  # linkedin: yourusername\
\
# Date format\
date_format: "%B %d, %Y"\
\
# Timezone\
timezone: Asia/Shanghai\
}